In [8]:
#importing libraries, I will use for cleaning and modifying the dataset
import pandas as pd
import matplotlib as pl

In [9]:
#reading csv file. Applied set_option to see full data in the series 
df = pd.read_csv(r'C:\Users\v-vovnenko\Desktop\python\us-software-engineer-jobs.csv', sep = ';')
pd.set_option('display.max_colwidth', 3000)
df

,title,company,salary,rating,review_count,types,state,location,hires_needed_exact,urgently_hiring,remote_work_model,new_job,hiring_event_job,indeed_apply_enabled,Unnamed: 14
0,Middle Web Developer,"Denios, Inc.","45,000 - 55,000 a year",0,0.0,Full-time,KY,"Louisville, KY",1.0,True,NaN,False,False,True,NaN
1,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Francisco Bay Area, CA",1.0,False,NaN,True,False,True,NaN
2,Software Engineer (Clearance Required),LOCKHEED MARTIN CORPORATION,"3,000 a week",4,8633.0,NaN,MD,"Annapolis Junction, MD",NaN,False,NaN,False,False,False,NaN
3,NaN,Goliath Solutions Group,15 - 20 an hour,0,0.0,Full-time,TX,"Fairview, TX",1.0,True,NaN,False,False,True,NaN
4,Middle DevOps Engineer - Very Profitable Start-up,TechTalent NW,"125,000 - 170,000 a year",0,0.0,Full-time,WA,"Bellevue, WA",1.0,False,REMOTE_COVID_TEMPORARY,True,False,True,NaN
5,Lead Software/Java Engineer,Bectran,"90,000 - 130,000 a year","1,5",4.0,Full-time,IL,"Chicago, IL",1.0,False,NaN,True,False,True,NaN
6,Senior Software Engineer,College Auto Sales of Florida,"105,271 - 126,000 a year",0,0.0,Full-time,FL,"Miami Lakes, FL",1.0,False,NaN,False,False,True,NaN
7,"Solutions Engineer, Software",Liberty Mutual Insurance,"128,200 - 177,600 a year","-3,6",4540.0,NaN,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,False,NaN
8,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Jose, CA",1.0,False,NaN,True,False,True,NaN
9,Software Engineer - Production Support - CCE - Mulesoft,Salesforce,"121,800 a year","4,3",767.0,Full-time,CO,"Denver, CO",NaN,False,NaN,False,False,False,NaN
10,"Software Engineer, Backend - Remote",Project Admission,"105,000 - 120,000 a year",0,0.0,Full-time,TN,"Nashville, TN",1.0,False,REMOTE_ALWAYS,False,False,True,NaN
11,Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning),Indeed,"109,000 - 159,000 a year","4,3",824.0,Full-time,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,True,NaN
12,Senior COBOL Developer (G67),Resource Management Associates LLC.,45 an hour,4,2.0,"Full-time, Temporary, Contract",GA,"Atlanta, GA",1.0,False,NaN,True,False,True,NaN
13,Senior ASP.NET Developer,Defy Medical,"115,000 - 130,000 a year","-2,9",10.0,Full-time,FL,"Tampa, FL",1.0,False,REMOTE_COVID_TEMPORARY,False,False,True,NaN
14,Senior Software Engineer,POPi/o Mobile Video Cloud,40 - 74 an hour,0,0.0,Full-time,UT,"Sandy, UT",2.0,True,NaN,False,False,True,NaN
15,Software/Firmware Engineer,CQENS Technologies Inc.,"90,000 - 150,000 a year",0,0.0,Full-time,NaN,California,1.0,False,REMOTE_ALWAYS,True,False,True,NaN
16,Embedded Software Developer - C/C++ Experience Required,Real Time Automation,"80,000 - 100,000 a year",0,0.0,Full-time,WI,"Fort Atkinson, WI",1.0,False,NaN,False,False,True,NaN
17,Head of Site Reliability Engineering,S&P Global,"148,200 - 338,600 a year","3,9",1354.0,NaN,NJ,"Princeton, NJ",NaN,False,NaN,False,False,False,NaN
18,Junior Production Support Software Engineer - Salesforce.org,Salesforce,"121,800 a year","4,3",767.0,Full-time,NaN,Texas,NaN,False,NaN,True,False,False,NaN
19,"Automation Engineer - Lorain, OH","Absolute Machine Tools, Inc.","55,000 - 85,000 a year",1,1.0,Full-time,OH,"Lorain, OH",2.0,False,NaN,False,False,True,NaN
20,Senior Site Reliability Engineer,Apto Payments,"120,000 - 180,000 a year",0,0.0,Full-time,NaN,Remote,1.0,True,NaN,False,False,True,NaN
21,Senior Full Stack Engineer,CyberCoders,"120,000 - 160,000 a year","3,4",47.0,Full-time,CO,"Denver, CO",NaN,False,NaN,True,False,True,NaN
22,Junior Application Developer,State of Montana,"68,000 - 78,000 a year","3,5",276.0,Full-time,MT,"Helena, MT",NaN,False,NaN,False,False,False,NaN
23,Sr. Mobile Automation Engineer,IT Giants Inc,40 - 60 an hour,0,0.0,Full-time,PA,"West Chester, PA",4.0,True,REMOTE_COVID_TEMPORARY,False,False,True,NaN
24,"Solutions Engineer, Software",Liberty Mutual Insurance,"150,000 - 200,000 a year","3,6",4540.0,NaN,NH,"Dover, NH",NaN,False,NaN,False,False,False,NaN
25,Software Programmer - Java,Flux Resources,71 - 77 an hour,"4,1",7.0,"Full-time, Contract",OR,"Portland, OR",1.0,True,NaN,True,False,True,NaN
26,Junior Software Engineer,Systems Automated,"70,000 - 90,000 a year",0,0.0,Full-time,TX,"Dallas, TX",1.0,False,NaN,False,False,True,NaN
27,Senior Software Engineer - Hiring Insights (Full Stack),Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,REMOTE_ALWAYS,False,False,True,NaN
28,Software Diagnostic Engineer,CyberCoders,"140,000 - 190,000 a year","3,4",47.0,Full-time,CA,"San Jose, CA",NaN,False,NaN,True,False,True,NaN
29,C# Senior Software Developer (Contractor) - Front Office Trading /Risk,DataAxxis,"900 - 1,000 a day",0,0.0,"Full-time, Contract",NY,"New York, NY",3.0,True,REMOTE_COVID_TEMPORARY,True,False,True,NaN
30,Senior Web Developer,FreeRateUpdate.com LLC,"100,000 - 120,000 a year",0,0.0,Full-time,PA,"Chadds Ford, PA",2.0,True,NaN,False,False,True,NaN
31,Software Engineer,Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,False,False,True,NaN
32,Middle Staff Software Engineer - Job Seeker API,Indeed,"164,000 - 239,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,True,False,True,NaN
33,React Developer,Thumbraise,"42,256 - 95,005 a year",0,0.0,Full-time,NaN,Remote,1.0,False,REMOTE_ALWAYS,False,False,True,NaN
34,Sr. Robotics Software Engineer,Decide,"100,000 - 140,000 a year",0,0.0,Full-time,MA,"Boston, MA",1.0,True,NaN,False,False,True,NaN
35,Senior Remote Software Engineer (Code: OP) 100% Remote,HK Tech,"90,000 a year",0,0.0,Full-time,UT,"Lindon, UT",NaN,False,REMOTE_ALWAYS,False,False,True,NaN
36,Senior Web Developer - .NET,SPN Solutions Inc.,"95,000 - 100,000 a year","-3,3",10.0,Full-time,MD,"Bethesda, MD",1.0,True,NaN,False,False,True,NaN
37,Site Reliability - Incident Commander,Salesforce,"121,800 a year","4,3",767.0,Full-time,CA,"San Francisco, CA",NaN,False,NaN,True,False,False,NaN
38,Middle Java Full Stack Developer,SkyWalkGlobalServices,75 - 85 an hour,0,0.0,"Full-time, Contract",NY,"New York, NY",1.0,False,REMOTE_ALWAYS,False,False,True,NaN
39,NaN,State of West Virginia,"36,779 - 68,041 a year","3,5",135.0,Full-time,WV,"Kanawha County, WV",NaN,False,NaN,False,False,False,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#checking an amount of rows snd columns in the dataframe
df.shape

(47, 15)

In [11]:
#droping the rows with NaN values in all series + a row without a value in a first serie
#resetting indexes after dropiing NaN rows
df.drop(df.index[36:47], inplace=True)
df.drop(df.index[3], inplace=True)
df.reset_index(drop = True, inplace=True)
df

,title,company,salary,rating,review_count,types,state,location,hires_needed_exact,urgently_hiring,remote_work_model,new_job,hiring_event_job,indeed_apply_enabled,Unnamed: 14
0,Middle Web Developer,"Denios, Inc.","45,000 - 55,000 a year",0,0.0,Full-time,KY,"Louisville, KY",1.0,True,NaN,False,False,True,NaN
1,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Francisco Bay Area, CA",1.0,False,NaN,True,False,True,NaN
2,Software Engineer (Clearance Required),LOCKHEED MARTIN CORPORATION,"3,000 a week",4,8633.0,NaN,MD,"Annapolis Junction, MD",NaN,False,NaN,False,False,False,NaN
3,Middle DevOps Engineer - Very Profitable Start-up,TechTalent NW,"125,000 - 170,000 a year",0,0.0,Full-time,WA,"Bellevue, WA",1.0,False,REMOTE_COVID_TEMPORARY,True,False,True,NaN
4,Lead Software/Java Engineer,Bectran,"90,000 - 130,000 a year","1,5",4.0,Full-time,IL,"Chicago, IL",1.0,False,NaN,True,False,True,NaN
5,Senior Software Engineer,College Auto Sales of Florida,"105,271 - 126,000 a year",0,0.0,Full-time,FL,"Miami Lakes, FL",1.0,False,NaN,False,False,True,NaN
6,"Solutions Engineer, Software",Liberty Mutual Insurance,"128,200 - 177,600 a year","-3,6",4540.0,NaN,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,False,NaN
7,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Jose, CA",1.0,False,NaN,True,False,True,NaN
8,Software Engineer - Production Support - CCE - Mulesoft,Salesforce,"121,800 a year","4,3",767.0,Full-time,CO,"Denver, CO",NaN,False,NaN,False,False,False,NaN
9,"Software Engineer, Backend - Remote",Project Admission,"105,000 - 120,000 a year",0,0.0,Full-time,TN,"Nashville, TN",1.0,False,REMOTE_ALWAYS,False,False,True,NaN
10,Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning),Indeed,"109,000 - 159,000 a year","4,3",824.0,Full-time,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,True,NaN
11,Senior COBOL Developer (G67),Resource Management Associates LLC.,45 an hour,4,2.0,"Full-time, Temporary, Contract",GA,"Atlanta, GA",1.0,False,NaN,True,False,True,NaN
12,Senior ASP.NET Developer,Defy Medical,"115,000 - 130,000 a year","-2,9",10.0,Full-time,FL,"Tampa, FL",1.0,False,REMOTE_COVID_TEMPORARY,False,False,True,NaN
13,Senior Software Engineer,POPi/o Mobile Video Cloud,40 - 74 an hour,0,0.0,Full-time,UT,"Sandy, UT",2.0,True,NaN,False,False,True,NaN
14,Software/Firmware Engineer,CQENS Technologies Inc.,"90,000 - 150,000 a year",0,0.0,Full-time,NaN,California,1.0,False,REMOTE_ALWAYS,True,False,True,NaN
15,Embedded Software Developer - C/C++ Experience Required,Real Time Automation,"80,000 - 100,000 a year",0,0.0,Full-time,WI,"Fort Atkinson, WI",1.0,False,NaN,False,False,True,NaN
16,Head of Site Reliability Engineering,S&P Global,"148,200 - 338,600 a year","3,9",1354.0,NaN,NJ,"Princeton, NJ",NaN,False,NaN,False,False,False,NaN
17,Junior Production Support Software Engineer - Salesforce.org,Salesforce,"121,800 a year","4,3",767.0,Full-time,NaN,Texas,NaN,False,NaN,True,False,False,NaN
18,"Automation Engineer - Lorain, OH","Absolute Machine Tools, Inc.","55,000 - 85,000 a year",1,1.0,Full-time,OH,"Lorain, OH",2.0,False,NaN,False,False,True,NaN
19,Senior Site Reliability Engineer,Apto Payments,"120,000 - 180,000 a year",0,0.0,Full-time,NaN,Remote,1.0,True,NaN,False,False,True,NaN
20,Senior Full Stack Engineer,CyberCoders,"120,000 - 160,000 a year","3,4",47.0,Full-time,CO,"Denver, CO",NaN,False,NaN,True,False,True,NaN
21,Junior Application Developer,State of Montana,"68,000 - 78,000 a year","3,5",276.0,Full-time,MT,"Helena, MT",NaN,False,NaN,False,False,False,NaN
22,Sr. Mobile Automation Engineer,IT Giants Inc,40 - 60 an hour,0,0.0,Full-time,PA,"West Chester, PA",4.0,True,REMOTE_COVID_TEMPORARY,False,False,True,NaN
23,"Solutions Engineer, Software",Liberty Mutual Insurance,"150,000 - 200,000 a year","3,6",4540.0,NaN,NH,"Dover, NH",NaN,False,NaN,False,False,False,NaN
24,Software Programmer - Java,Flux Resources,71 - 77 an hour,"4,1",7.0,"Full-time, Contract",OR,"Portland, OR",1.0,True,NaN,True,False,True,NaN
25,Junior Software Engineer,Systems Automated,"70,000 - 90,000 a year",0,0.0,Full-time,TX,"Dallas, TX",1.0,False,NaN,False,False,True,NaN
26,Senior Software Engineer - Hiring Insights (Full Stack),Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,REMOTE_ALWAYS,False,False,True,NaN
27,Software Diagnostic Engineer,CyberCoders,"140,000 - 190,000 a year","3,4",47.0,Full-time,CA,"San Jose, CA",NaN,False,NaN,True,False,True,NaN
28,C# Senior Software Developer (Contractor) - Front Office Trading /Risk,DataAxxis,"900 - 1,000 a day",0,0.0,"Full-time, Contract",NY,"New York, NY",3.0,True,REMOTE_COVID_TEMPORARY,True,False,True,NaN
29,Senior Web Developer,FreeRateUpdate.com LLC,"100,000 - 120,000 a year",0,0.0,Full-time,PA,"Chadds Ford, PA",2.0,True,NaN,False,False,True,NaN
30,Software Engineer,Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,False,False,True,NaN
31,Middle Staff Software Engineer - Job Seeker API,Indeed,"164,000 - 239,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,True,False,True,NaN
32,React Developer,Thumbraise,"42,256 - 95,005 a year",0,0.0,Full-time,NaN,Remote,1.0,False,REMOTE_ALWAYS,False,False,True,NaN
33,Sr. Robotics Software Engineer,Decide,"100,000 - 140,000 a year",0,0.0,Full-time,MA,"Boston, MA",1.0,True,NaN,False,False,True,NaN
34,Senior Remote Software Engineer (Code: OP) 100% Remote,HK Tech,"90,000 a year",0,0.0,Full-time,UT,"Lindon, UT",NaN,False,REMOTE_ALWAYS,False,False,True,NaN

In [12]:
#replacing 'Sr.' to 'Senior' in the column 'title'
df['title'].replace('Sr.', 'Senior', regex = True)

0                                                       Middle Web Developer
1                                      Real-Time, Embedded Software Engineer
2                                     Software Engineer (Clearance Required)
3                          Middle DevOps Engineer - Very Profitable Start-up
4                                                Lead Software/Java Engineer
5                                                   Senior Software Engineer
6                                               Solutions Engineer, Software
7                                      Real-Time, Embedded Software Engineer
8                    Software Engineer - Production Support - CCE - Mulesoft
9                                        Software Engineer, Backend - Remote
10     Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning)
11                                              Senior COBOL Developer (G67)
12                                                  Senior ASP.NET Developer
13                                                  Senior Software Engineer
14                                                Software/Firmware Engineer
15                   Embedded Software Developer - C/C++ Experience Required
16                                      Head of Site Reliability Engineering
17              Junior Production Support Software Engineer - Salesforce.org
18                                          Automation Engineer - Lorain, OH
19                                          Senior Site Reliability Engineer
20                                                Senior Full Stack Engineer
21                                              Junior Application Developer
22                                         Senior Mobile Automation Engineer
23                                              Solutions Engineer, Software
24                                                Software Programmer - Java
25                                                  Junior Software Engineer
26                   Senior Software Engineer - Hiring Insights (Full Stack)
27                                              Software Diagnostic Engineer
28    C# Senior Software Developer (Contractor) - Front Office Trading /Risk
29                                                      Senior Web Developer
30                                                         Software Engineer
31                           Middle Staff Software Engineer - Job Seeker API
32                                                           React Developer
33                                         Senior Robotics Software Engineer
34                    Senior Remote Software Engineer (Code: OP) 100% Remote
Name: title, dtype: object

In [13]:
#choosing all titles which start from 'Junior', 'Middle', Senior'
Junior_Middle_Senior_titles = df['title'].str.contains('Junior|Middle|Senior')
titles = df[Junior_Middle_Senior_titles]
titles

,title,company,salary,rating,review_count,types,state,location,hires_needed_exact,urgently_hiring,remote_work_model,new_job,hiring_event_job,indeed_apply_enabled,Unnamed: 14
0,Middle Web Developer,"Denios, Inc.","45,000 - 55,000 a year",0,0.0,Full-time,KY,"Louisville, KY",1.0,True,NaN,False,False,True,NaN
3,Middle DevOps Engineer - Very Profitable Start-up,TechTalent NW,"125,000 - 170,000 a year",0,0.0,Full-time,WA,"Bellevue, WA",1.0,False,REMOTE_COVID_TEMPORARY,True,False,True,NaN
5,Senior Software Engineer,College Auto Sales of Florida,"105,271 - 126,000 a year",0,0.0,Full-time,FL,"Miami Lakes, FL",1.0,False,NaN,False,False,True,NaN
10,Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning),Indeed,"109,000 - 159,000 a year","4,3",824.0,Full-time,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,True,NaN
11,Senior COBOL Developer (G67),Resource Management Associates LLC.,45 an hour,4,2.0,"Full-time, Temporary, Contract",GA,"Atlanta, GA",1.0,False,NaN,True,False,True,NaN
12,Senior ASP.NET Developer,Defy Medical,"115,000 - 130,000 a year","-2,9",10.0,Full-time,FL,"Tampa, FL",1.0,False,REMOTE_COVID_TEMPORARY,False,False,True,NaN
13,Senior Software Engineer,POPi/o Mobile Video Cloud,40 - 74 an hour,0,0.0,Full-time,UT,"Sandy, UT",2.0,True,NaN,False,False,True,NaN
17,Junior Production Support Software Engineer - Salesforce.org,Salesforce,"121,800 a year","4,3",767.0,Full-time,NaN,Texas,NaN,False,NaN,True,False,False,NaN
19,Senior Site Reliability Engineer,Apto Payments,"120,000 - 180,000 a year",0,0.0,Full-time,NaN,Remote,1.0,True,NaN,False,False,True,NaN
20,Senior Full Stack Engineer,CyberCoders,"120,000 - 160,000 a year","3,4",47.0,Full-time,CO,"Denver, CO",NaN,False,NaN,True,False,True,NaN
21,Junior Application Developer,State of Montana,"68,000 - 78,000 a year","3,5",276.0,Full-time,MT,"Helena, MT",NaN,False,NaN,False,False,False,NaN
25,Junior Software Engineer,Systems Automated,"70,000 - 90,000 a year",0,0.0,Full-time,TX,"Dallas, TX",1.0,False,NaN,False,False,True,NaN
26,Senior Software Engineer - Hiring Insights (Full Stack),Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,REMOTE_ALWAYS,False,False,True,NaN
28,C# Senior Software Developer (Contractor) - Front Office Trading /Risk,DataAxxis,"900 - 1,000 a day",0,0.0,"Full-time, Contract",NY,"New York, NY",3.0,True,REMOTE_COVID_TEMPORARY,True,False,True,NaN
29,Senior Web Developer,FreeRateUpdate.com LLC,"100,000 - 120,000 a year",0,0.0,Full-time,PA,"Chadds Ford, PA",2.0,True,NaN,False,False,True,NaN
31,Middle Staff Software Engineer - Job Seeker API,Indeed,"164,000 - 239,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,True,False,True,NaN
34,Senior Remote Software Engineer (Code: OP) 100% Remote,HK Tech,"90,000 a year",0,0.0,Full-time,UT,"Lindon, UT",NaN,False,REMOTE_ALWAYS,False,False,True,NaN

In [14]:
df['seniority level'] = titles['title'].str.split(' '). str[0]

In [15]:
#df.dtypes
df['seniority level'].memory_usage()

412

In [22]:
#memory dropped from 412 to 371
df['seniority level'] = df['seniority level'].astype('category')
df['seniority level'].memory_usage()

371

In [18]:
df['company'] = df['company'].str.title()
df

,title,company,salary,rating,review_count,types,state,location,hires_needed_exact,urgently_hiring,remote_work_model,new_job,hiring_event_job,indeed_apply_enabled,Unnamed: 14,seniority level
0,Middle Web Developer,"Denios, Inc.","45,000 - 55,000 a year",0,0.0,Full-time,KY,"Louisville, KY",1.0,True,NaN,False,False,True,NaN,Middle
1,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Francisco Bay Area, CA",1.0,False,NaN,True,False,True,NaN,NaN
2,Software Engineer (Clearance Required),Lockheed Martin Corporation,"3,000 a week",4,8633.0,NaN,MD,"Annapolis Junction, MD",NaN,False,NaN,False,False,False,NaN,NaN
3,Middle DevOps Engineer - Very Profitable Start-up,Techtalent Nw,"125,000 - 170,000 a year",0,0.0,Full-time,WA,"Bellevue, WA",1.0,False,REMOTE_COVID_TEMPORARY,True,False,True,NaN,Middle
4,Lead Software/Java Engineer,Bectran,"90,000 - 130,000 a year","1,5",4.0,Full-time,IL,"Chicago, IL",1.0,False,NaN,True,False,True,NaN,NaN
5,Senior Software Engineer,College Auto Sales Of Florida,"105,271 - 126,000 a year",0,0.0,Full-time,FL,"Miami Lakes, FL",1.0,False,NaN,False,False,True,NaN,Senior
6,"Solutions Engineer, Software",Liberty Mutual Insurance,"128,200 - 177,600 a year","-3,6",4540.0,NaN,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,False,NaN,NaN
7,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Jose, CA",1.0,False,NaN,True,False,True,NaN,NaN
8,Software Engineer - Production Support - CCE - Mulesoft,Salesforce,"121,800 a year","4,3",767.0,Full-time,CO,"Denver, CO",NaN,False,NaN,False,False,False,NaN,NaN
9,"Software Engineer, Backend - Remote",Project Admission,"105,000 - 120,000 a year",0,0.0,Full-time,TN,"Nashville, TN",1.0,False,REMOTE_ALWAYS,False,False,True,NaN,NaN
10,Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning),Indeed,"109,000 - 159,000 a year","4,3",824.0,Full-time,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior
11,Senior COBOL Developer (G67),Resource Management Associates Llc.,45 an hour,4,2.0,"Full-time, Temporary, Contract",GA,"Atlanta, GA",1.0,False,NaN,True,False,True,NaN,Senior
12,Senior ASP.NET Developer,Defy Medical,"115,000 - 130,000 a year","-2,9",10.0,Full-time,FL,"Tampa, FL",1.0,False,REMOTE_COVID_TEMPORARY,False,False,True,NaN,Senior
13,Senior Software Engineer,Popi/O Mobile Video Cloud,40 - 74 an hour,0,0.0,Full-time,UT,"Sandy, UT",2.0,True,NaN,False,False,True,NaN,Senior
14,Software/Firmware Engineer,Cqens Technologies Inc.,"90,000 - 150,000 a year",0,0.0,Full-time,NaN,California,1.0,False,REMOTE_ALWAYS,True,False,True,NaN,NaN
15,Embedded Software Developer - C/C++ Experience Required,Real Time Automation,"80,000 - 100,000 a year",0,0.0,Full-time,WI,"Fort Atkinson, WI",1.0,False,NaN,False,False,True,NaN,NaN
16,Head of Site Reliability Engineering,S&P Global,"148,200 - 338,600 a year","3,9",1354.0,NaN,NJ,"Princeton, NJ",NaN,False,NaN,False,False,False,NaN,NaN
17,Junior Production Support Software Engineer - Salesforce.org,Salesforce,"121,800 a year","4,3",767.0,Full-time,NaN,Texas,NaN,False,NaN,True,False,False,NaN,Junior
18,"Automation Engineer - Lorain, OH","Absolute Machine Tools, Inc.","55,000 - 85,000 a year",1,1.0,Full-time,OH,"Lorain, OH",2.0,False,NaN,False,False,True,NaN,NaN
19,Senior Site Reliability Engineer,Apto Payments,"120,000 - 180,000 a year",0,0.0,Full-time,NaN,Remote,1.0,True,NaN,False,False,True,NaN,Senior
20,Senior Full Stack Engineer,Cybercoders,"120,000 - 160,000 a year","3,4",47.0,Full-time,CO,"Denver, CO",NaN,False,NaN,True,False,True,NaN,Senior
21,Junior Application Developer,State Of Montana,"68,000 - 78,000 a year","3,5",276.0,Full-time,MT,"Helena, MT",NaN,False,NaN,False,False,False,NaN,Junior
22,Sr. Mobile Automation Engineer,It Giants Inc,40 - 60 an hour,0,0.0,Full-time,PA,"West Chester, PA",4.0,True,REMOTE_COVID_TEMPORARY,False,False,True,NaN,NaN
23,"Solutions Engineer, Software",Liberty Mutual Insurance,"150,000 - 200,000 a year","3,6",4540.0,NaN,NH,"Dover, NH",NaN,False,NaN,False,False,False,NaN,NaN
24,Software Programmer - Java,Flux Resources,71 - 77 an hour,"4,1",7.0,"Full-time, Contract",OR,"Portland, OR",1.0,True,NaN,True,False,True,NaN,NaN
25,Junior Software Engineer,Systems Automated,"70,000 - 90,000 a year",0,0.0,Full-time,TX,"Dallas, TX",1.0,False,NaN,False,False,True,NaN,Junior
26,Senior Software Engineer - Hiring Insights (Full Stack),Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior
27,Software Diagnostic Engineer,Cybercoders,"140,000 - 190,000 a year","3,4",47.0,Full-time,CA,"San Jose, CA",NaN,False,NaN,True,False,True,NaN,NaN
28,C# Senior Software Developer (Contractor) - Front Office Trading /Risk,Dataaxxis,"900 - 1,000 a day",0,0.0,"Full-time, Contract",NY,"New York, NY",3.0,True,REMOTE_COVID_TEMPORARY,True,False,True,NaN,C#
29,Senior Web Developer,Freerateupdate.Com Llc,"100,000 - 120,000 a year",0,0.0,Full-time,PA,"Chadds Ford, PA",2.0,True,NaN,False,False,True,NaN,Senior
30,Software Engineer,Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,False,False,True,NaN,NaN
31,Middle Staff Software Engineer - Job Seeker API,Indeed,"164,000 - 239,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,True,False,True,NaN,Middle
32,React Developer,Thumbraise,"42,256 - 95,005 a year",0,0.0,Full-time,NaN,Remote,1.0,False,REMOTE_ALWAYS,False,False,True,NaN,NaN
33,Sr. Robotics Software Engineer,Decide,"100,000 - 140,000 a year",0,0.0,Full-time,MA,"Boston, MA",1.0,True,NaN,False,False,True,NaN,NaN
34,Senior Remote Software Engineer (Code: OP) 100% Remote,Hk Tech,"90,000 a year",0,0.0,Full-time,UT,"Lindon, UT",NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior

In [19]:
#replacing a symbol '-' with ''
df['rating'] = df['rating'].astype(str).str.replace('-', '')
df

,title,company,salary,rating,review_count,types,state,location,hires_needed_exact,urgently_hiring,remote_work_model,new_job,hiring_event_job,indeed_apply_enabled,Unnamed: 14,seniority level
0,Middle Web Developer,"Denios, Inc.","45,000 - 55,000 a year",0,0.0,Full-time,KY,"Louisville, KY",1.0,True,NaN,False,False,True,NaN,Middle
1,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Francisco Bay Area, CA",1.0,False,NaN,True,False,True,NaN,NaN
2,Software Engineer (Clearance Required),Lockheed Martin Corporation,"3,000 a week",4,8633.0,NaN,MD,"Annapolis Junction, MD",NaN,False,NaN,False,False,False,NaN,NaN
3,Middle DevOps Engineer - Very Profitable Start-up,Techtalent Nw,"125,000 - 170,000 a year",0,0.0,Full-time,WA,"Bellevue, WA",1.0,False,REMOTE_COVID_TEMPORARY,True,False,True,NaN,Middle
4,Lead Software/Java Engineer,Bectran,"90,000 - 130,000 a year","1,5",4.0,Full-time,IL,"Chicago, IL",1.0,False,NaN,True,False,True,NaN,NaN
5,Senior Software Engineer,College Auto Sales Of Florida,"105,271 - 126,000 a year",0,0.0,Full-time,FL,"Miami Lakes, FL",1.0,False,NaN,False,False,True,NaN,Senior
6,"Solutions Engineer, Software",Liberty Mutual Insurance,"128,200 - 177,600 a year","3,6",4540.0,NaN,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,False,NaN,NaN
7,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,"San Jose, CA",1.0,False,NaN,True,False,True,NaN,NaN
8,Software Engineer - Production Support - CCE - Mulesoft,Salesforce,"121,800 a year","4,3",767.0,Full-time,CO,"Denver, CO",NaN,False,NaN,False,False,False,NaN,NaN
9,"Software Engineer, Backend - Remote",Project Admission,"105,000 - 120,000 a year",0,0.0,Full-time,TN,"Nashville, TN",1.0,False,REMOTE_ALWAYS,False,False,True,NaN,NaN
10,Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning),Indeed,"109,000 - 159,000 a year","4,3",824.0,Full-time,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior
11,Senior COBOL Developer (G67),Resource Management Associates Llc.,45 an hour,4,2.0,"Full-time, Temporary, Contract",GA,"Atlanta, GA",1.0,False,NaN,True,False,True,NaN,Senior
12,Senior ASP.NET Developer,Defy Medical,"115,000 - 130,000 a year","2,9",10.0,Full-time,FL,"Tampa, FL",1.0,False,REMOTE_COVID_TEMPORARY,False,False,True,NaN,Senior
13,Senior Software Engineer,Popi/O Mobile Video Cloud,40 - 74 an hour,0,0.0,Full-time,UT,"Sandy, UT",2.0,True,NaN,False,False,True,NaN,Senior
14,Software/Firmware Engineer,Cqens Technologies Inc.,"90,000 - 150,000 a year",0,0.0,Full-time,NaN,California,1.0,False,REMOTE_ALWAYS,True,False,True,NaN,NaN
15,Embedded Software Developer - C/C++ Experience Required,Real Time Automation,"80,000 - 100,000 a year",0,0.0,Full-time,WI,"Fort Atkinson, WI",1.0,False,NaN,False,False,True,NaN,NaN
16,Head of Site Reliability Engineering,S&P Global,"148,200 - 338,600 a year","3,9",1354.0,NaN,NJ,"Princeton, NJ",NaN,False,NaN,False,False,False,NaN,NaN
17,Junior Production Support Software Engineer - Salesforce.org,Salesforce,"121,800 a year","4,3",767.0,Full-time,NaN,Texas,NaN,False,NaN,True,False,False,NaN,Junior
18,"Automation Engineer - Lorain, OH","Absolute Machine Tools, Inc.","55,000 - 85,000 a year",1,1.0,Full-time,OH,"Lorain, OH",2.0,False,NaN,False,False,True,NaN,NaN
19,Senior Site Reliability Engineer,Apto Payments,"120,000 - 180,000 a year",0,0.0,Full-time,NaN,Remote,1.0,True,NaN,False,False,True,NaN,Senior
20,Senior Full Stack Engineer,Cybercoders,"120,000 - 160,000 a year","3,4",47.0,Full-time,CO,"Denver, CO",NaN,False,NaN,True,False,True,NaN,Senior
21,Junior Application Developer,State Of Montana,"68,000 - 78,000 a year","3,5",276.0,Full-time,MT,"Helena, MT",NaN,False,NaN,False,False,False,NaN,Junior
22,Sr. Mobile Automation Engineer,It Giants Inc,40 - 60 an hour,0,0.0,Full-time,PA,"West Chester, PA",4.0,True,REMOTE_COVID_TEMPORARY,False,False,True,NaN,NaN
23,"Solutions Engineer, Software",Liberty Mutual Insurance,"150,000 - 200,000 a year","3,6",4540.0,NaN,NH,"Dover, NH",NaN,False,NaN,False,False,False,NaN,NaN
24,Software Programmer - Java,Flux Resources,71 - 77 an hour,"4,1",7.0,"Full-time, Contract",OR,"Portland, OR",1.0,True,NaN,True,False,True,NaN,NaN
25,Junior Software Engineer,Systems Automated,"70,000 - 90,000 a year",0,0.0,Full-time,TX,"Dallas, TX",1.0,False,NaN,False,False,True,NaN,Junior
26,Senior Software Engineer - Hiring Insights (Full Stack),Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior
27,Software Diagnostic Engineer,Cybercoders,"140,000 - 190,000 a year","3,4",47.0,Full-time,CA,"San Jose, CA",NaN,False,NaN,True,False,True,NaN,NaN
28,C# Senior Software Developer (Contractor) - Front Office Trading /Risk,Dataaxxis,"900 - 1,000 a day",0,0.0,"Full-time, Contract",NY,"New York, NY",3.0,True,REMOTE_COVID_TEMPORARY,True,False,True,NaN,C#
29,Senior Web Developer,Freerateupdate.Com Llc,"100,000 - 120,000 a year",0,0.0,Full-time,PA,"Chadds Ford, PA",2.0,True,NaN,False,False,True,NaN,Senior
30,Software Engineer,Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,False,False,True,NaN,NaN
31,Middle Staff Software Engineer - Job Seeker API,Indeed,"164,000 - 239,000 a year","4,3",824.0,Full-time,WA,"Seattle, WA",NaN,False,NaN,True,False,True,NaN,Middle
32,React Developer,Thumbraise,"42,256 - 95,005 a year",0,0.0,Full-time,NaN,Remote,1.0,False,REMOTE_ALWAYS,False,False,True,NaN,NaN
33,Sr. Robotics Software Engineer,Decide,"100,000 - 140,000 a year",0,0.0,Full-time,MA,"Boston, MA",1.0,True,NaN,False,False,True,NaN,NaN
34,Senior Remote Software Engineer (Code: OP) 100% Remote,Hk Tech,"90,000 a year",0,0.0,Full-time,UT,"Lindon, UT",NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior

In [20]:
#removing state in the column 'location'
df['location'] = df['location'].str.split(',').apply(lambda x: x[0])
df

,title,company,salary,rating,review_count,types,state,location,hires_needed_exact,urgently_hiring,remote_work_model,new_job,hiring_event_job,indeed_apply_enabled,Unnamed: 14,seniority level
0,Middle Web Developer,"Denios, Inc.","45,000 - 55,000 a year",0,0.0,Full-time,KY,Louisville,1.0,True,NaN,False,False,True,NaN,Middle
1,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,San Francisco Bay Area,1.0,False,NaN,True,False,True,NaN,NaN
2,Software Engineer (Clearance Required),Lockheed Martin Corporation,"3,000 a week",4,8633.0,NaN,MD,Annapolis Junction,NaN,False,NaN,False,False,False,NaN,NaN
3,Middle DevOps Engineer - Very Profitable Start-up,Techtalent Nw,"125,000 - 170,000 a year",0,0.0,Full-time,WA,Bellevue,1.0,False,REMOTE_COVID_TEMPORARY,True,False,True,NaN,Middle
4,Lead Software/Java Engineer,Bectran,"90,000 - 130,000 a year","1,5",4.0,Full-time,IL,Chicago,1.0,False,NaN,True,False,True,NaN,NaN
5,Senior Software Engineer,College Auto Sales Of Florida,"105,271 - 126,000 a year",0,0.0,Full-time,FL,Miami Lakes,1.0,False,NaN,False,False,True,NaN,Senior
6,"Solutions Engineer, Software",Liberty Mutual Insurance,"128,200 - 177,600 a year","3,6",4540.0,NaN,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,False,NaN,NaN
7,"Real-Time, Embedded Software Engineer",Checkmate Partners,"100,000 - 200,000 a year",0,0.0,Full-time,CA,San Jose,1.0,False,NaN,True,False,True,NaN,NaN
8,Software Engineer - Production Support - CCE - Mulesoft,Salesforce,"121,800 a year","4,3",767.0,Full-time,CO,Denver,NaN,False,NaN,False,False,False,NaN,NaN
9,"Software Engineer, Backend - Remote",Project Admission,"105,000 - 120,000 a year",0,0.0,Full-time,TN,Nashville,1.0,False,REMOTE_ALWAYS,False,False,True,NaN,NaN
10,Senior Software Engineer - Enterprise Team (Full-Stack/Front-Leaning),Indeed,"109,000 - 159,000 a year","4,3",824.0,Full-time,NaN,Remote,NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior
11,Senior COBOL Developer (G67),Resource Management Associates Llc.,45 an hour,4,2.0,"Full-time, Temporary, Contract",GA,Atlanta,1.0,False,NaN,True,False,True,NaN,Senior
12,Senior ASP.NET Developer,Defy Medical,"115,000 - 130,000 a year","2,9",10.0,Full-time,FL,Tampa,1.0,False,REMOTE_COVID_TEMPORARY,False,False,True,NaN,Senior
13,Senior Software Engineer,Popi/O Mobile Video Cloud,40 - 74 an hour,0,0.0,Full-time,UT,Sandy,2.0,True,NaN,False,False,True,NaN,Senior
14,Software/Firmware Engineer,Cqens Technologies Inc.,"90,000 - 150,000 a year",0,0.0,Full-time,NaN,California,1.0,False,REMOTE_ALWAYS,True,False,True,NaN,NaN
15,Embedded Software Developer - C/C++ Experience Required,Real Time Automation,"80,000 - 100,000 a year",0,0.0,Full-time,WI,Fort Atkinson,1.0,False,NaN,False,False,True,NaN,NaN
16,Head of Site Reliability Engineering,S&P Global,"148,200 - 338,600 a year","3,9",1354.0,NaN,NJ,Princeton,NaN,False,NaN,False,False,False,NaN,NaN
17,Junior Production Support Software Engineer - Salesforce.org,Salesforce,"121,800 a year","4,3",767.0,Full-time,NaN,Texas,NaN,False,NaN,True,False,False,NaN,Junior
18,"Automation Engineer - Lorain, OH","Absolute Machine Tools, Inc.","55,000 - 85,000 a year",1,1.0,Full-time,OH,Lorain,2.0,False,NaN,False,False,True,NaN,NaN
19,Senior Site Reliability Engineer,Apto Payments,"120,000 - 180,000 a year",0,0.0,Full-time,NaN,Remote,1.0,True,NaN,False,False,True,NaN,Senior
20,Senior Full Stack Engineer,Cybercoders,"120,000 - 160,000 a year","3,4",47.0,Full-time,CO,Denver,NaN,False,NaN,True,False,True,NaN,Senior
21,Junior Application Developer,State Of Montana,"68,000 - 78,000 a year","3,5",276.0,Full-time,MT,Helena,NaN,False,NaN,False,False,False,NaN,Junior
22,Sr. Mobile Automation Engineer,It Giants Inc,40 - 60 an hour,0,0.0,Full-time,PA,West Chester,4.0,True,REMOTE_COVID_TEMPORARY,False,False,True,NaN,NaN
23,"Solutions Engineer, Software",Liberty Mutual Insurance,"150,000 - 200,000 a year","3,6",4540.0,NaN,NH,Dover,NaN,False,NaN,False,False,False,NaN,NaN
24,Software Programmer - Java,Flux Resources,71 - 77 an hour,"4,1",7.0,"Full-time, Contract",OR,Portland,1.0,True,NaN,True,False,True,NaN,NaN
25,Junior Software Engineer,Systems Automated,"70,000 - 90,000 a year",0,0.0,Full-time,TX,Dallas,1.0,False,NaN,False,False,True,NaN,Junior
26,Senior Software Engineer - Hiring Insights (Full Stack),Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,Seattle,NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior
27,Software Diagnostic Engineer,Cybercoders,"140,000 - 190,000 a year","3,4",47.0,Full-time,CA,San Jose,NaN,False,NaN,True,False,True,NaN,NaN
28,C# Senior Software Developer (Contractor) - Front Office Trading /Risk,Dataaxxis,"900 - 1,000 a day",0,0.0,"Full-time, Contract",NY,New York,3.0,True,REMOTE_COVID_TEMPORARY,True,False,True,NaN,C#
29,Senior Web Developer,Freerateupdate.Com Llc,"100,000 - 120,000 a year",0,0.0,Full-time,PA,Chadds Ford,2.0,True,NaN,False,False,True,NaN,Senior
30,Software Engineer,Indeed,"132,000 - 192,000 a year","4,3",824.0,Full-time,WA,Seattle,NaN,False,NaN,False,False,True,NaN,NaN
31,Middle Staff Software Engineer - Job Seeker API,Indeed,"164,000 - 239,000 a year","4,3",824.0,Full-time,WA,Seattle,NaN,False,NaN,True,False,True,NaN,Middle
32,React Developer,Thumbraise,"42,256 - 95,005 a year",0,0.0,Full-time,NaN,Remote,1.0,False,REMOTE_ALWAYS,False,False,True,NaN,NaN
33,Sr. Robotics Software Engineer,Decide,"100,000 - 140,000 a year",0,0.0,Full-time,MA,Boston,1.0,True,NaN,False,False,True,NaN,NaN
34,Senior Remote Software Engineer (Code: OP) 100% Remote,Hk Tech,"90,000 a year",0,0.0,Full-time,UT,Lindon,NaN,False,REMOTE_ALWAYS,False,False,True,NaN,Senior

In [6]:
df['seniority level'] = df['seniority level'].astype('category')

NameError: name 'df' is not defined